apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: streamx-grafana-route
  namespace: prometheus-stack
spec:
  http:
    - name: streamx-grafana-route
      match:
        hosts:
          - grafana.demo-puresight-starter.streamx.site
        paths:
          - /*
      priority: 20
      backends:
        - serviceName: prometheus-stack-grafana
          servicePort: 80