defaults:
  global:
    imagePullSecrets:
      - name: "streamx-demo-pull-secret"
    resources:
      requests:
        cpu: 300m
        memory: 512Mi
  ingestion:
    replicas: 0
  processing:
    replicas: 0
  delivery:
    replicas: 3
    podDisruptionBudget:
      enabled: true
      minAvailable: 1

delivery:
  blueprint-web:
    ingress:
      enabled: true
      hosts:
        - host: china-demo.streamx.site
          paths:
            - servicePort: 8084
              path: /*
      tls:
        - hosts:
            - china-demo.streamx.site
          secretName: blueprint-web.crt
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-cert-cluster-issuer"
    probes:
      readiness:
        httpGet:
          path: /q/health/ready
          port: 8080
        initialDelaySeconds: 3
        timeoutSeconds: 2
        periodSeconds: 5
        successThreshold: 1
        failureThreshold: 3
      startup:
        httpGet:
          path: /q/health/started
          port: 8080
        initialDelaySeconds: 10
        timeoutSeconds: 2
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 10
    components:
      webserver:
        probes:
          readiness:
            httpGet:
              path: /health
              port: 80
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          liveness:
            httpGet:
              path: /health
              port: 80
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          startup:
            httpGet:
              path: /health
              port: 80
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
  blueprint-search:
    ingress:
      enabled: true
      hosts:
        - host: china-demo.streamx.site
          paths:
            - path: /search/*
      tls:
        - hosts:
            - china-demo.streamx.site
          secretName: blueprint-search.crt
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-cert-cluster-issuer"
    probes:
      readiness:
        httpGet:
          path: /q/health/ready
          port: 8080
        initialDelaySeconds: 3
        timeoutSeconds: 2
        periodSeconds: 5
        successThreshold: 1
        failureThreshold: 3
      startup:
        httpGet:
          path: /q/health/started
          port: 8080
        initialDelaySeconds: 10
        timeoutSeconds: 2
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 10
    components:
      opensearch:
        sidecar: true
        probes:
          readiness:
            httpGet:
              path: /
              port: 9201
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          liveness:
            httpGet:
              path: /
              port: 9201
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          startup:
            httpGet:
              path: /
              port: 9201
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
