service:
  type: LoadBalancer
  loadBalancerIP: 52.157.197.105
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: demo-puresight-starter

ingress-controller:
  enabled: true

dashboard:
  enabled: true

apisix:
  ssl:
    enabled: true