apiVersion: apps/v1
kind: Deployment
metadata:
  name: exporter-detached-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exporter-detached-service
  template:
    metadata:
      labels:
        app: exporter-detached-service
    spec:
      containers:
        - name: exporter-detached-service
          image: ghcr.io/streamx-dev/streamx-blueprints/exporter-detached-service:2.0.1-jvm
          ports:
            - containerPort: 8080
          env:
            - name: PULSAR_CLIENT_SERVICEURL
              value: "pulsar://pulsar-broker.kaap.svc.cluster.local:6650"
            - name: PULSAR_ADMIN_SERVICEURL
              value: "http://pulsar-broker.kaap.svc.cluster.local:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: exporter-detached-service
spec:
  selector:
    app: exporter-detached-service
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: exporter-detached-service
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cert-cluster-issuer
spec:
  ingressClassName: apisix
  tls:
    - hosts:
        - export.${streamx.accelerator.web.host}
      secretName: blueprint-exporter.crt
  rules:
    - host: export.${streamx.accelerator.web.host}
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: exporter-detached-service
                port:
                  number: 80