apiVersion: streamx.dev/v1alpha1
kind: MeshFederation
metadata:
  name: sx
spec:
  targets:
    byoc-puresight-edge-cn-beijing-alicloud:
      clusterRole: edge
      matchClusterNames:
        - byoc-puresight-edge-cn-beijing-alicloud
      overlay:
        defaults:
          delivery:
            storageClassName: alicloud-disk-efficiency
        delivery:
          blueprint-search:
            components:
              opensearch:
                sidecar: true
                volumes:
                  opensearch-data:
                    mountPath: /usr/share/opensearch/data
                    size: 20Gi
            ingress:
              enabled: true
              hosts:
                - host: >-
                    ds-puresight-web.byoc-puresight-edge-cn-beijing-alicloud.streamx.cloud
                  paths:
                    - path: /search/*
              tls:
                - hosts:
                    - >-
                      ds-puresight-web.byoc-puresight-edge-cn-beijing-alicloud.streamx.cloud
                  secretName: wildcard-streamx-cloud.crt
            volumes:
              rocksdb:
                mountPath: /var/lib/rocksdb
                size: 20Gi
          blueprint-web:
            ingress:
              enabled: true
              hosts:
                - host: >-
                    ds-puresight-web.byoc-puresight-edge-cn-beijing-alicloud.streamx.cloud
                  paths:
                    - path: /*
                      servicePort: 8084
              tls:
                - hosts:
                    - >-
                      ds-puresight-web.byoc-puresight-edge-cn-beijing-alicloud.streamx.cloud
                  secretName: wildcard-streamx-cloud.crt
            volumes:
              repository-volume:
                mountPath: /var/lib/rocksdb
                size: 20Gi
              rocksdb:
                mountPath: /var/lib/rocksdb
                size: 20Gi
      priority: 10
    byoc-ds-edge-alicloud-beijing:
      clusterRole: edge
      matchClusterNames:
        - byoc-ds-edge-alicloud-beijing
      overlay:
        defaults:
          delivery:
            storageClassName: "alicloud-disk-efficiency"
        delivery:
          blueprint-search:
            volumes:
              rocksdb:
                mountPath: "${streamx.rocksdb.path}"
                size: 20Gi
            ingress:
              enabled: true
              hosts:
                - host: ds-puresight-web.byoc-ds-edge-alicloud-beijing.streamx.cloud
                  paths:
                    - path: /search/*
              tls:
                - hosts:
                    - >-
                      ds-puresight-web.byoc-ds-edge-alicloud-beijing.streamx.cloud
                  secretName: wildcard-streamx-cloud.crt
            components:
              opensearch:
                sidecar: true
                volumes:
                  opensearch-data:
                    mountPath: /usr/share/opensearch/data
                    size: 20Gi
          blueprint-web:
            volumes:
              repository-volume:
                mountPath: "${streamx.rocksdb.path}"
                size: 20Gi
              rocksdb:
                mountPath: "${streamx.rocksdb.path}"
                size: 20Gi
            ingress:
              enabled: true
              hosts:
                - host: ds-puresight-web.byoc-ds-edge-alicloud-beijing.streamx.cloud
                  paths:
                    - path: /*
                      servicePort: 8084
              tls:
                - hosts:
                    - >-
                      ds-puresight-web.byoc-ds-edge-alicloud-beijing.streamx.cloud
                  secretName: wildcard-streamx-cloud.crt
      priority: 10
    edge-ap-southeast-1:
      clusterRole: edge
      matchClusterNames:
        - edge-ap-southeast-1
      overlay:
        defaults:
          delivery:
            storageClassName: "hcloud-volumes"
        delivery:
          blueprint-search:
            ingress:
              enabled: true
              hosts:
                - host: ds-puresight-web.edge-ap-southeast-1.streamx.cloud
                  paths:
                    - path: /search/*
              tls:
                - hosts:
                    - ds-puresight-web.edge-ap-southeast-1.streamx.cloud
                  secretName: wildcard-streamx-cloud.crt
          blueprint-web:
            ingress:
              enabled: true
              hosts:
                - host: ds-puresight-web.edge-ap-southeast-1.streamx.cloud
                  paths:
                    - path: /*
                      servicePort: 8084
              tls:
                - hosts:
                    - ds-puresight-web.edge-ap-southeast-1.streamx.cloud
                  secretName: wildcard-streamx-cloud.crt
      priority: 10
    edge-eu-central-1:
      clusterRole: edge
      matchClusterNames:
        - edge-eu-central-1
      overlay:
        defaults:
          delivery:
            storageClassName: "hcloud-volumes"
        delivery:
          blueprint-search:
            ingress:
              enabled: true
              hosts:
                - host: ds-puresight-web.edge-eu-central-1.streamx.cloud
                  paths:
                    - path: /search/*
              tls:
                - hosts:
                    - ds-puresight-web.edge-eu-central-1.streamx.cloud
                  secretName: wildcard-streamx-cloud.crt
          blueprint-web:
            ingress:
              enabled: true
              hosts:
                - host: ds-puresight-web.edge-eu-central-1.streamx.cloud
                  paths:
                    - path: /*
                      servicePort: 8084
              tls:
                - hosts:
                    - ds-puresight-web.edge-eu-central-1.streamx.cloud
                  secretName: wildcard-streamx-cloud.crt
      priority: 10
    edge-us-east-1:
      clusterRole: edge
      matchClusterNames:
        - edge-us-east-1
      overlay:
        defaults:
          delivery:
            storageClassName: "hcloud-volumes"
        delivery:
          blueprint-search:
            ingress:
              enabled: true
              hosts:
                - host: ds-puresight-web.edge-us-east-1.streamx.cloud
                  paths:
                    - path: /search/*
              tls:
                - hosts:
                    - ds-puresight-web.edge-us-east-1.streamx.cloud
                  secretName: wildcard-streamx-cloud.crt
          blueprint-web:
            ingress:
              enabled: true
              hosts:
                - host: ds-puresight-web.edge-us-east-1.streamx.cloud
                  paths:
                    - path: /*
                      servicePort: 8084
              tls:
                - hosts:
                    - ds-puresight-web.edge-us-east-1.streamx.cloud
                  secretName: wildcard-streamx-cloud.crt
      priority: 10
    edge-us-west-1:
      clusterRole: edge
      matchClusterNames:
        - edge-us-west-1
      overlay:
        defaults:
          delivery:
            storageClassName: "hcloud-volumes"
        delivery:
          blueprint-search:
            ingress:
              enabled: true
              hosts:
                - host: ds-puresight-web.edge-us-west-1.streamx.cloud
                  paths:
                    - path: /search/*
              tls:
                - hosts:
                    - ds-puresight-web.edge-us-west-1.streamx.cloud
                  secretName: wildcard-streamx-cloud.crt
          blueprint-web:
            ingress:
              enabled: true
              hosts:
                - host: ds-puresight-web.edge-us-west-1.streamx.cloud
                  paths:
                    - path: /*
                      servicePort: 8084
              tls:
                - hosts:
                    - ds-puresight-web.edge-us-west-1.streamx.cloud
                  secretName: wildcard-streamx-cloud.crt
      priority: 10
    processing-eu-central-1:
      clusterRole: processing
      matchClusterNames:
        - processing-eu-central-1
      overlay:
        defaults:
          processing:
            storageClassName: "hcloud-volumes"
        ingestion:
          rest-ingestion:
            ingress:
              enabled: true
              hosts:
                - host: >-
                    ds-puresight-ingestion.processing-eu-central-1.streamx.cloud
                  paths:
                    - path: /*
              tls:
                - hosts:
                    - >-
                      ds-puresight-ingestion.processing-eu-central-1.streamx.cloud
                  secretName: wildcard-streamx-cloud.crt
      priority: 10
