image:
  repository: crpi-ynub1f3ynqwgpy46.cn-hangzhou.personal.cr.aliyuncs.com/streamx-demo/streamx-operator
  tag: 0.0.12-jvm
imagePullSecrets:
  - name: streamx-demo-pull-secret

messaging:
  pulsar:
    initImage: "crpi-ynub1f3ynqwgpy46.cn-hangzhou.personal.cr.aliyuncs.com/streamx-demo/pulsar-init:latest-jvm"
    clientServiceUrl: "pulsar://10.0.119.192:6650"
    adminServiceUrl: "http://10.0.119.192:8080"