defaults:
  global:
    resources:
      requests:
        cpu: 300m
        memory: 512Mi
  ingestion:
    replicas: ${streamx.default.ingestion.replicas}
    podDisruptionBudget:
      enabled: ${streamx.default.ingestion.podDisruptionBudget.enabled}
      minAvailable: 1
  processing:
    replicas: ${streamx.default.processing.replicas}
  delivery:
    replicas: ${streamx.default.delivery.replicas}
    podDisruptionBudget:
      enabled: true
      minAvailable: 1


ingestion:
  rest-ingestion:
    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: "500m"
        cert-manager.io/cluster-issuer: "lets-encrypt-staging-cluster-issuer"
      hosts:
        - host: ${streamx.accelerator.ingestion.host}
          paths:
            - path: /*
      tls:
        - hosts:
            - ${streamx.accelerator.ingestion.host}
          secretName: rest-ingestion.crt
delivery:
  blueprint-web:
    ingress:
      enabled: true
      hosts:
        - host: ${streamx.accelerator.web.host}
          paths:
            - servicePort: 8084
              path: /*
      tls:
        - hosts:
            - ${streamx.accelerator.web.host}
          secretName: delivery.crt
      annotations:
        cert-manager.io/cluster-issuer: "lets-encrypt-staging-cluster-issuer"
    probes:
      # readiness:
      #   httpGet:
      #     path: /q/health/ready
      #     port: 8080
      #   initialDelaySeconds: 3
      #   timeoutSeconds: 2
      #   periodSeconds: 5
      #   successThreshold: 1
      # Failures should not put the service offline
      #   failureThreshold: 604800
      liveness:
        httpGet:
          path: /q/health/live
          port: 8080
        initialDelaySeconds: 10
        timeoutSeconds: 2
        periodSeconds: 5
        successThreshold: 1
        # Restart quick on exception to restore broken connection fast
        failureThreshold: 1
      startup:
        httpGet:
          path: /q/health/started
          port: 8080
        initialDelaySeconds: 10
        timeoutSeconds: 2
        periodSeconds: 10
        successThreshold: 1
        # Let's wait ~ 110 seconds for the connection to be established
        failureThreshold: 10
    components:
      webserver:
        probes:
          readiness:
            httpGet:
              path: /health
              port: 80
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          liveness:
            httpGet:
              path: /health
              port: 80
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          startup:
            httpGet:
              path: /health
              port: 80
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
  blueprint-search:
    ingress:
      enabled: true
      hosts:
        - host: ${streamx.accelerator.web.host}
          paths:
            - path: /search/*
      tls:
        - hosts:
            - ${streamx.accelerator.web.host}
          secretName: delivery.crt
      annotations:
        cert-manager.io/cluster-issuer: "lets-encrypt-staging-cluster-issuer"
    probes:
      # readiness:
      #   httpGet:
      #     path: /q/health/ready
      #     port: 8080
      #   initialDelaySeconds: 3
      #   timeoutSeconds: 2
      #   periodSeconds: 5
      #   successThreshold: 1
        # Failures should not put the service offline
      #   failureThreshold: 604800
      liveness:
        httpGet:
          path: /q/health/live
          port: 8080
        initialDelaySeconds: 10
        timeoutSeconds: 2
        periodSeconds: 5
        successThreshold: 1
        # Restart quick on exception to restore broken connection fast
        failureThreshold: 1
      startup:
        httpGet:
          path: /q/health/started
          port: 8080
        initialDelaySeconds: 10
        timeoutSeconds: 2
        periodSeconds: 10
        successThreshold: 1
        # Let's wait ~ 110 seconds for the connection to be established
        failureThreshold: 10
    components:
      opensearch:
        sidecar: false
        probes:
          readiness:
            httpGet:
              path: /
              port: 9201
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          liveness:
            httpGet:
              path: /
              port: 9201
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          startup:
            httpGet:
              path: /
              port: 9201
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
