defaults:
  global:
    resources:
      requests:
        cpu: 300m
        memory: 512Mi
  ingestion:
    replicas: ${streamx.default.ingestion.replicas}
    podDisruptionBudget:
      enabled: true
      minAvailable: 1
  processing:
    replicas: ${streamx.default.processing.replicas}
  delivery:
    replicas: ${streamx.default.delivery.replicas}
    podDisruptionBudget:
      enabled: true
      minAvailable: 1


ingestion:
  rest-ingestion:
    ingress:
      enabled: true
      hosts:
        - host: ${streamx.accelerator.ingestion.host}
          paths:
            - path: /*
      tls:
        - hosts:
            - ${streamx.accelerator.ingestion.host}
delivery:
  blueprint-web:
    stateful: false
    ingress:
      enabled: true
      hosts:
        - host: ${streamx.accelerator.web.host}
          paths:
            - servicePort: 8084
              path: /*
      tls:
        - hosts:
            - ${streamx.accelerator.web.host}
          secretName: wildcard-streamx-cloud.crt
    probes:
      startup:
        httpGet:
          path: /q/health/started
          port: 8080
        initialDelaySeconds: 10
        timeoutSeconds: 2
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 120
    components:
      webserver:
        probes:
          readiness:
            httpGet:
              path: /health
              port: 80
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          liveness:
            httpGet:
              path: /health
              port: 80
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          startup:
            httpGet:
              path: /health
              port: 80
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
  blueprint-search:
    stateful: false
    replicas: 1
    podDisruptionBudget:
      enabled: false
    ingress:
      enabled: true
      hosts:
        - host: ${streamx.accelerator.web.host}
          paths:
            - path: /search/*
      tls:
        - hosts:
            - ${streamx.accelerator.web.host}
          secretName: wildcard-streamx-cloud.crt
    probes:
      startup:
        httpGet:
          path: /q/health/started
          port: 8080
        initialDelaySeconds: 10
        timeoutSeconds: 2
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 120
    components:
      opensearch:
        sidecar: true
        volumes:
          opensearch-data:
            mountPath: /usr/share/opensearch/data
            size: 10Gi
        probes:
          readiness:
            httpGet:
              path: /
              port: 9201
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          liveness:
            httpGet:
              path: /
              port: 9201
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          startup:
            httpGet:
              path: /
              port: 9201
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
